-- Bind model providers and models to workspaces.

CREATE TABLE mate_model_provider_scoped (
    id                         BIGINT       GENERATED BY DEFAULT AS IDENTITY(START WITH 903000000000000000) NOT NULL PRIMARY KEY,
    workspace_id               BIGINT       NOT NULL DEFAULT 1,
    provider_id                VARCHAR(64)  NOT NULL,
    name                       VARCHAR(128) NOT NULL,
    api_key_prefix             VARCHAR(32),
    chat_model                 VARCHAR(64),
    api_key                    VARCHAR(512) NOT NULL DEFAULT '',
    base_url                   VARCHAR(512),
    generate_kwargs            TEXT,
    is_custom                  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_local                   BOOLEAN      NOT NULL DEFAULT FALSE,
    support_model_discovery    BOOLEAN      NOT NULL DEFAULT FALSE,
    support_connection_check   BOOLEAN      NOT NULL DEFAULT FALSE,
    freeze_url                 BOOLEAN      NOT NULL DEFAULT FALSE,
    require_api_key            BOOLEAN      NOT NULL DEFAULT TRUE,
    auth_type                  VARCHAR(16)  NOT NULL DEFAULT 'api_key',
    oauth_access_token         TEXT,
    oauth_refresh_token        TEXT,
    oauth_expires_at           BIGINT,
    oauth_account_id           VARCHAR(128),
    fallback_priority          INT          DEFAULT 0,
    enabled                    BOOLEAN      DEFAULT FALSE,
    create_time                DATETIME     NOT NULL,
    update_time                DATETIME     NOT NULL,
    CONSTRAINT uk_model_provider_workspace_provider UNIQUE (workspace_id, provider_id)
);

INSERT INTO mate_model_provider_scoped (
    id, workspace_id, provider_id, name, api_key_prefix, chat_model, api_key, base_url,
    generate_kwargs, is_custom, is_local, support_model_discovery, support_connection_check,
    freeze_url, require_api_key, auth_type, oauth_access_token, oauth_refresh_token,
    oauth_expires_at, oauth_account_id, fallback_priority, enabled, create_time, update_time
)
SELECT
    900000000000000000 + ROW_NUMBER() OVER (ORDER BY provider_id),
    1, provider_id, name, api_key_prefix, chat_model, COALESCE(api_key, ''), base_url,
    generate_kwargs, is_custom, is_local, support_model_discovery, support_connection_check,
    freeze_url, require_api_key, auth_type, oauth_access_token, oauth_refresh_token,
    oauth_expires_at, oauth_account_id, fallback_priority, enabled, create_time, update_time
  FROM mate_model_provider;

DROP TABLE mate_model_provider;
ALTER TABLE mate_model_provider_scoped RENAME TO mate_model_provider;

INSERT INTO mate_model_provider (
    id, workspace_id, provider_id, name, api_key_prefix, chat_model, api_key, base_url,
    generate_kwargs, is_custom, is_local, support_model_discovery, support_connection_check,
    freeze_url, require_api_key, auth_type, oauth_access_token, oauth_refresh_token,
    oauth_expires_at, oauth_account_id, fallback_priority, enabled, create_time, update_time
)
SELECT
    901000000000000000 + ROW_NUMBER() OVER (ORDER BY w.id, p.provider_id),
    w.id, p.provider_id, p.name, p.api_key_prefix, p.chat_model, '',
    p.base_url, p.generate_kwargs, p.is_custom, p.is_local,
    p.support_model_discovery, p.support_connection_check, p.freeze_url,
    p.require_api_key, p.auth_type, NULL, NULL, NULL, NULL,
    p.fallback_priority, p.enabled, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  FROM mate_workspace w
  JOIN mate_model_provider p ON p.workspace_id = 1
 WHERE w.id <> 1
   AND NOT EXISTS (
       SELECT 1 FROM mate_model_provider existing
        WHERE existing.workspace_id = w.id
          AND existing.provider_id = p.provider_id
   );

ALTER TABLE mate_model_config ADD COLUMN IF NOT EXISTS workspace_id BIGINT NOT NULL DEFAULT 1;

INSERT INTO mate_model_config (
    id, workspace_id, name, provider, model_name, description, temperature, max_tokens,
    top_p, builtin, enabled, is_default, max_input_tokens, enable_search, search_strategy,
    model_type, modalities, request_timeout_seconds, create_time, update_time, deleted
)
SELECT
    902000000000000000 + ROW_NUMBER() OVER (ORDER BY w.id, m.id),
    w.id, m.name, m.provider, m.model_name, m.description, m.temperature, m.max_tokens,
    m.top_p, m.builtin, m.enabled, m.is_default, m.max_input_tokens, m.enable_search,
    m.search_strategy, m.model_type, m.modalities, m.request_timeout_seconds,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, m.deleted
  FROM mate_workspace w
  JOIN mate_model_config m ON m.workspace_id = 1
 WHERE w.id <> 1
   AND NOT EXISTS (
       SELECT 1 FROM mate_model_config existing
        WHERE existing.workspace_id = w.id
          AND existing.provider = m.provider
          AND existing.model_name = m.model_name
          AND existing.deleted = m.deleted
   );

CREATE INDEX IF NOT EXISTS idx_model_config_workspace_provider
    ON mate_model_config(workspace_id, provider, model_name);
CREATE INDEX IF NOT EXISTS idx_model_config_workspace_default
    ON mate_model_config(workspace_id, is_default, enabled);
