-- V135: Provider token quota defaults.

CREATE TABLE IF NOT EXISTS mate_provider_token_quota (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY(START WITH 904000000000000000) NOT NULL PRIMARY KEY,
    workspace_id  BIGINT       NOT NULL,
    provider_id   VARCHAR(64)  NOT NULL,
    limit_tokens  BIGINT       NOT NULL,
    used_tokens   BIGINT       NOT NULL DEFAULT 0,
    create_time   DATETIME     NOT NULL,
    update_time   DATETIME     NOT NULL,
    CONSTRAINT uk_provider_token_quota_workspace_provider UNIQUE (workspace_id, provider_id)
);

INSERT INTO mate_provider_token_quota (workspace_id, provider_id, limit_tokens, used_tokens, create_time, update_time)
SELECT w.id, 'dashscope', 2000000, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  FROM mate_workspace w
 WHERE NOT EXISTS (
       SELECT 1 FROM mate_provider_token_quota q
        WHERE q.workspace_id = w.id AND q.provider_id = 'dashscope'
   );

INSERT INTO mate_provider_token_quota (workspace_id, provider_id, limit_tokens, used_tokens, create_time, update_time)
SELECT w.id, 'deepseek', 3000000, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
  FROM mate_workspace w
 WHERE NOT EXISTS (
       SELECT 1 FROM mate_provider_token_quota q
        WHERE q.workspace_id = w.id AND q.provider_id = 'deepseek'
   );
